"""Actual original/staged whole native cache wrapper differential, work-only.

Run storage stage then stage-shared-danger-packet.py first. No production write,
full DLL/game call or timing claim. --emit-only writes fixture C++ without builds.
"""
from pathlib import Path
import hashlib,json,os,re,subprocess,sys
root=Path(__file__).resolve().parents[1];core=root/'CvGameCoreDLL_Expansion2';out=root/'work/shared-packet-native-regression';out.mkdir(exist_ok=True)
stage=root/'work/shared-packet-candidate';manifest=json.loads((stage/'manifest.json').read_text(encoding='utf-8'));production='--production' in sys.argv
for n,h in manifest['candidate_sha256'].items():assert hashlib.sha256((stage/n).read_text(encoding='utf-8-sig').encode()).hexdigest()==h,'Stale stage '+n
live={n:(core/n).read_text(encoding='utf-8-sig') for n in manifest['candidate_sha256']}
if production:
 for n,s in live.items():assert hashlib.sha256(s.encode()).hexdigest()==manifest['candidate_sha256'][n],'Current production does not exactly match reviewed stage: '+n
# The tracked numerical fixture generator supplies only actual body extraction
# and deterministic services. Execute its pure generation prefix, not tests or
# compiler/process code, and never depend on a generated C++ file.
generator=(root/'work/test-shared-danger-packet.py').read_text(encoding='utf-8-sig');prefix=generator[:generator.index("tests=r'''")]
prefix=prefix.replace("current={n:(core/n).read_text(encoding='utf-8-sig') for n in files}","current={n:subprocess.check_output(['git','show',control+':CvGameCoreDLL_Expansion2/'+n],cwd=root).decode('utf-8-sig').replace('\\r\\n','\\n') for n in files}",1)
scope={'__file__':str(root/'work/test-shared-danger-packet.py')};exec(compile(prefix,'tracked shared-packet fixture generation','exec'),scope)
function=scope['function'];base=scope['base'];headers=scope['headers'];services=scope['services']
services=services.replace('static bool OnDangerRefresh();','static bool OnDangerRefresh();static void OnUnitLookup();static void OnDescriptorCopy();static void OnAirLoadingCallback();',1)
base=base.replace('const CvUnit*getUnit(int i)const{','const CvUnit*getUnit(int i)const{OnUnitLookup();',1)
# Callback hook is a deterministic service, not a mutation added to actual code.
base='static void OnUnitLookup();static void OnAirLoadingCallback();\n'+base
base=base.replace('OnLeaf();Record(3,a->id,d->id);','OnLeaf();if(a->domain==DOMAIN_AIR&&!a->IsCanAttackRanged())OnAirLoadingCallback();Record(3,a->id,d->id);',1)
base=base.replace('static bool failAllocation=false;','static bool failAllocation=false;static size_t failAtAllocation=0;',1)
base=base.replace('if(failAllocation)throw std::bad_alloc();','if(failAllocation||allocationCalls==failAtAllocation)throw std::bad_alloc();',1)
services=services.replace('bool ActualProbeSources(const CvPlot&,int*,unsigned,unsigned&)const;','bool ActualProbeSources(const CvPlot&,int*,unsigned,unsigned&)const;\n bool NativeCacheDescriptor(const CvPlot&,int*,unsigned,unsigned&)const;\n bool AppendStackDangerCacheDescriptor(const CvPlot&p,int*w,unsigned c,unsigned&u)const{bool ok=NativeCacheDescriptor(p,w,c,u);if(ok)OnDescriptorCopy();return ok;}',1)
services=services.replace(' bool TryGetPlanSamplingContext(unsigned long&,long&);',' bool TryGetPlanSamplingContext(unsigned long&serial,long&epoch){if(!planSamples.enabled||planSamples.depth!=1||planSamples.epoch!=ReadPlanSampleEpoch())return false;serial=planSamples.serial;epoch=planSamples.epoch;return true;}',1)
old=subprocess.check_output(['git','show',manifest['control']+':CvGameCoreDLL_Expansion2/CvTacticalAI.cpp'],cwd=root).decode('utf-8-sig').replace('\r\n','\n')
new=live['CvTacticalAI.cpp'] if production else (stage/'CvTacticalAI.cpp').read_text(encoding='utf-8-sig')
danger=live['CvDangerPlots.cpp'] if production else (stage/'CvDangerPlots.cpp').read_text(encoding='utf-8-sig')
common=scope['implementation'].split('struct StackForecastKey\n')[0]
common+='\n'+function(danger,'bool CvDangerPlots::AppendStackDangerProbeSources(').replace('AppendStackDangerProbeSources','ActualProbeSources',1)
common+='\n'+function(danger,'bool CvDangerPlots::AppendStackDangerCacheDescriptor(').replace('AppendStackDangerCacheDescriptor','NativeCacheDescriptor',1)
def cache_module(text,trial):
 value=text[text.index('struct StackForecastKey\n'):text.index('// Bind immutable inputs only')]
 value+='\n'+function(text,'struct StackDangerOutcomeBatch\n')+';\n'
 if trial:value+='\n'+text[text.index('static bool AppendUniquePacketDamage('):text.index('static int GetCachedStackDanger(')]
 else:
  body=function(text,'static int GetCachedStackDanger(')
  body=re.sub(r'^.*PacketProbeCall packetProbeCall.*\n|^.*packetProbeCall\.Finish\(\).*\n','',body,flags=re.M)
  body=re.sub(r'result = \(packetProbeCall\.MarkRaw\(\), (.*?)\); // PLAN_PACKET_PROBE_DIAGNOSTIC_ONLY',r'result = \1;',body)
  value+='\n'+body;return value
 value+='\n'+function(text,'static int GetCachedStackDanger(');return value
implementation=common+'\nnamespace Control{\n'+cache_module(old,False)+'\n}\nnamespace Trial{\n'+cache_module(new,True)+'\n}\n'
tests=r'''
static unsigned checks=0,failures=0,leafCalls=0,leafMutation=0,prepMutation=0,descriptorMutation=0,airLoadingCallbacks=0;static unsigned seed=728199;static CvUnit*refreshAA=NULL;
static unsigned Next(){seed=seed*1664525u+1013904223u;return seed;}
static void Check(const char*n,bool ok){++checks;if(!ok){++failures;if(failures<25)printf("FAIL %s\n",n);}}
static void OnUnitLookup(){if(prepMutation){unsigned m=prepMutation;prepMutation=0;if(m==1)CvStackingStrengthCache::Invalidate();else if(m==2)++Trial::gStackForecastRevision;else if(m==3)maps[0].m_bDirty=true;else if(m==4)maps[0].m_DangerPlots[0].m_iFogCount+=2;}}
static void OnDescriptorCopy(){if(descriptorMutation){unsigned m=descriptorMutation;descriptorMutation=0;if(m==1)CvStackingStrengthCache::Invalidate();else if(m==2)++Trial::gStackForecastRevision;else if(m==3)maps[0].m_bDirty=true;else if(m==4)maps[0].m_DangerPlots[0].m_iFogCount+=2;else if(m==5)maps[0].m_DangerPlots[0].m_pPlot->getPlotCity()->hp=1;}}
static void OnAirLoadingCallback(){++airLoadingCallbacks;}
static void OnLeaf(){++leafCalls;if(leafMutation){unsigned m=leafMutation;leafMutation=0;if(m==1)CvStackingStrengthCache::Invalidate();else if(m==2)++Trial::gStackForecastRevision;else if(m==3)maps[0].m_DangerPlots[0].m_iFogCount+=2;else if(m==4)throw 19;else if(m==5)maps[0].m_DangerPlots[0].m_pPlot->getPlotCity()->hp=1;}}
static bool OnDangerRefresh(){if(MOD_EVENTS_CITY_BOMBARD&&refreshAA){++refreshAA->made;return true;}return false;}
static void Reset(){for(int p=0;p<4;++p){players[p]=CvPlayer();players[p].id=players[p].team=p;maps[p]=CvDangerPlots();for(int q=0;q<4;++q){teams[p].open[q]=false;if(p!=q)players[p].enemies.push_back(q);}}}
static void Invariant(){size_t bytes=0;bool ok=Trial::gStackDangerForecasts.size()==Trial::gStackDangerOrder.size()&&Trial::gStackDefenderForecasts.size()==Trial::gStackDefenderOrder.size();for(Trial::StackDangerForecasts::const_iterator i=Trial::gStackDangerForecasts.begin();i!=Trial::gStackDangerForecasts.end();++i)bytes+=Trial::StackDangerForecastPayloadBytes(*i);for(Trial::StackDefenderForecasts::const_iterator i=Trial::gStackDefenderForecasts.begin();i!=Trial::gStackDefenderForecasts.end();++i)bytes+=i->first.state.capacity()*sizeof(int);Check("actual native retained capacity/FIFO invariant",ok&&bytes==Trial::gStackKeyPayloadBytes&&bytes<=Trial::gStackKeyPayloadLimit&&Trial::gStackDangerForecasts.size()+Trial::gStackDefenderForecasts.size()<=Trial::gStackEntryLimit);}
static void Limits(size_t entries,size_t bytes){Control::gStackEntryLimit=Trial::gStackEntryLimit=entries;Control::gStackKeyPayloadLimit=Trial::gStackKeyPayloadLimit=bytes;}
struct ForeignArgs{CvUnit*unit;CvPlot*plot;vector<const CvUnit*>*roster;SUnitIDValueContainer*damage;};
static DWORD WINAPI ForeignNative(void*p){ForeignArgs*a=(ForeignArgs*)p;unsigned hits=Trial::gStackDangerHits,pk=Trial::gStackPacketHits,builds=Trial::gStackPacketBuilds;size_t bytes=Trial::gStackKeyPayloadBytes,entries=Trial::gStackDangerForecasts.size();Trial::GetCachedStackDanger(a->unit,a->plot,*a->roster,*a->damage,*a->damage);Check("native foreign thread does not mutate owned cache/counters",hits==Trial::gStackDangerHits&&pk==Trial::gStackPacketHits&&builds==Trial::gStackPacketBuilds&&bytes==Trial::gStackKeyPayloadBytes&&entries==Trial::gStackDangerForecasts.size());return 0;}
int main(){Check("native x86",sizeof(void*)==4);CvPlot target(0),nearby(1);CvCity city(7,0,&target),enemyCity(8,1,&nearby);CvUnit units[6],actors[9];
 for(int state=0;state<320;++state){Reset();CvDangerPlotContents&c=maps[0].m_DangerPlots[0];c.m_pPlot=&target;c.m_iFogCount=state%5;c.m_iImprovementDamage=state%17;c.m_bFlatPlotDamage=state%2!=0;target.city=state%3==0?&city:NULL;city.hp=20+Next()%280;city.protection=Next()%91;CvStacking::enabled=state%11!=0;CvStacking::selectionEnabled=state%7!=0;vector<const CvUnit*>r;SUnitIDValueContainer f,e;
  for(int i=0;i<6;++i){units[i]=CvUnit(i==0?0:i==1?-8:10+i,0,&target);units[i].hp=25+Next()%100;units[i].maxHP=units[i].hp+Next()%50;units[i].ranged=Next()%2!=0;units[i].defense=10+Next()%70;units[i].anti=Next()%2!=0;units[i].flankTarget=Next()%2!=0;units[i].terrainIgnore=Next()%2!=0;units[i].featureIgnore=Next()%2!=0;units[i].chance=Next()%151;units[i].domain=i==5?DOMAIN_AIR:DOMAIN_LAND;players[0].units[units[i].id]=&units[i];players[0].possible.push_back(make_pair(units[i].id,0));if(i<5)r.push_back(&units[i]);f.SetValue(units[i].id,(int)(Next()%141)-10);}CvUnit aa(99,0,&nearby);aa.domain=DOMAIN_AIR;aa.strength=400;players[0].units[99]=&aa;players[0].possible.push_back(make_pair(99,0));f.SetValue(99,(int)(Next()%111));city.garrison=&units[state%5];if(state%4==0)r.push_back(&units[1]);if(state%7==0)reverse(r.begin(),r.end());
  for(int i=0;i<9;++i){actors[i]=CvUnit(i%5,1+i%2,&nearby);actors[i].ranged=Next()%2!=0;actors[i].domain=i%4==0?DOMAIN_AIR:DOMAIN_LAND;actors[i].flank=Next()%2!=0;actors[i].aoe=Next()%4;actors[i].collateralLimit=Next()%5;actors[i].evasion=Next()%101;actors[i].strength=30+Next()%80;players[actors[i].owner].units[actors[i].id]=&actors[i];c.m_apUnits.push_back(make_pair(actors[i].owner,actors[i].id));e.SetValue(actors[i].id,(int)(Next()%71));}players[1].cities[8]=&enemyCity;c.m_apCities.push_back(make_pair(1,8));if(state%5==0)c.m_apCities.push_back(make_pair(1,8));
  Control::StackForecastScope control;Trial::StackForecastScope trial;Limits(5+state%6,500+state%8*250);Control::StackImmutableEnemyDamageScope oldDamage(e);Trial::StackImmutableEnemyDamageScope newDamage(e);
  for(int q=0;q<18;++q){const CvUnit*u=&units[q%6];int mean=c.GetStackDanger(u,r,f,e),old=Control::GetCachedStackDanger(u,&target,r,f,e),value=Trial::GetCachedStackDanger(u,&target,r,f,e);Check("whole old/new wrapper numeric exact",mean==old&&value==old);Invariant();}
 }
 Reset();CvStacking::enabled=CvStacking::selectionEnabled=true;target.city=NULL;vector<const CvUnit*>r;SUnitIDValueContainer none;
 for(int i=0;i<5;++i){units[i]=CvUnit(10+i,0,&target);units[i].hp=units[i].maxHP=500;players[0].units[10+i]=&units[i];r.push_back(&units[i]);}CvDangerPlotContents&c=maps[0].m_DangerPlots[0];c.m_pPlot=&target;actors[0]=CvUnit(44,1,&nearby);actors[0].ranged=true;actors[0].collateralLimit=0;players[1].units[44]=&actors[0];c.m_apUnits.push_back(make_pair(1,44));
 {Control::StackForecastScope old;Trial::StackForecastScope trial;Limits(12,4000);unsigned before=leafCalls;for(int q=0;q<5;++q)Control::GetCachedStackDanger(&units[q],&target,r,none,none);unsigned originalLeaves=leafCalls-before;before=leafCalls;for(int q=0;q<5;++q)Check("shared member ints exact",Trial::GetCachedStackDanger(&units[q],&target,r,none,none)==c.GetStackDanger(&units[q],r,none,none));Check("native wrapper one build/four shared hits",originalLeaves==5&&leafCalls-before==6&&Trial::gStackPacketBuilds==1&&Trial::gStackPacketHits==4);for(int q=0;q<5;++q){unsigned hits=Trial::gStackDangerHits,builds=Trial::gStackPacketBuilds,pkt=Trial::gStackPacketHits;size_t alloc=allocationCalls;Trial::GetCachedStackDanger(&units[q],&target,r,none,none);Check("native scalar hit no packet prepare/allocation",Trial::gStackDangerHits==hits+1&&Trial::gStackPacketBuilds==builds&&Trial::gStackPacketHits==pkt&&allocationCalls==alloc);}Invariant();}
 {Trial::StackForecastScope trial;Trial::gStackEntryLimit=1;Trial::gStackKeyPayloadLimit=4000;Trial::GetCachedStackDanger(&units[0],&target,r,none,none);Check("native one-entry budget retains queried even key",Trial::gStackDangerForecasts.size()==1&&Trial::gStackDangerForecasts.begin()->first.state.size()%2==0);Invariant();}
 for(size_t bytes=0;bytes<=900;bytes+=30){Trial::StackForecastScope trial;Trial::gStackEntryLimit=5;Trial::gStackKeyPayloadLimit=bytes;for(int q=0;q<5;++q)Check("native budgets cannot change result",Trial::GetCachedStackDanger(&units[q],&target,r,none,none)==c.GetStackDanger(&units[q],r,none,none));Invariant();}
 for(int mode=1;mode<=4;++mode){Trial::StackForecastScope trial;Trial::gStackEntryLimit=12;Trial::gStackKeyPayloadLimit=4000;Trial::GetCachedStackDanger(&units[0],&target,r,none,none);unsigned hits=Trial::gStackPacketHits;prepMutation=mode;unsigned raw=rawSequences,before=leafCalls;int got=Trial::GetCachedStackDanger(&units[1],&target,r,none,none);unsigned actualLeaves=leafCalls-before;Check("native post-key invalidation rejects stale packet",Trial::gStackPacketHits==hits&&actualLeaves==1&&got==c.GetStackDanger(&units[1],r,none,none)&&(mode==4||rawSequences==raw+1));maps[0].m_bDirty=false;}
 for(int mode=1;mode<=4;++mode){Trial::StackForecastScope trial;Trial::gStackEntryLimit=12;Trial::gStackKeyPayloadLimit=4000;Trial::GetCachedStackDanger(&units[0],&target,r,none,none);unsigned hits=Trial::gStackPacketHits;descriptorMutation=mode;unsigned before=leafCalls;int value=Trial::GetCachedStackDanger(&units[1],&target,r,none,none);Check("native mutation AFTER source copy rejects stale packet",Trial::gStackPacketHits==hits&&leafCalls==before+1&&value==c.GetStackDanger(&units[1],r,none,none));maps[0].m_bDirty=false;}
 for(int mode=1;mode<=3;++mode){Trial::StackForecastScope trial;Trial::gStackEntryLimit=12;Trial::gStackKeyPayloadLimit=4000;leafMutation=mode;unsigned before=leafCalls;Trial::GetCachedStackDanger(&units[0],&target,r,none,none);Check("native invalidated computed result returned once",leafCalls==before+1&&Trial::gStackDangerForecasts.empty());Invariant();}
 {Trial::StackForecastScope trial;leafMutation=4;bool caught=false;try{Trial::GetCachedStackDanger(&units[0],&target,r,none,none);}catch(int){caught=true;}Check("native exception releases scalar/packet loans",caught&&!Trial::gStackPacketScratchBusy&&!Trial::gStackDangerScratchBusy&&Trial::gStackDangerForecasts.empty());}
 {Trial::StackForecastScope trial;Trial::StackDangerOutcomeBatch batch(&target,r,none,none);unsigned before=leafCalls;for(int q=0;q<5;++q)Trial::GetCachedStackDanger(&units[q],&target,r,none,none,&batch);Check("native local batch never duplicated",leafCalls==before+1&&batch.ready);Invariant();}
 {Trial::StackForecastScope trial;CvUnit aa(99,0,&nearby);aa.domain=DOMAIN_AIR;aa.strength=500;players[0].units[99]=&aa;players[0].possible.push_back(make_pair(99,0));actors[0].domain=DOMAIN_AIR;Trial::GetCachedStackDanger(&units[0],&target,r,none,none);unsigned hits=Trial::gStackPacketHits;long epoch=CvStackingStrengthCache::SceneEpoch();MOD_EVENTS_CITY_BOMBARD=true;refreshAA=&aa;maps[0].m_bDirty=true;unsigned refresh=refreshCalls;int got=Trial::GetCachedStackDanger(&units[1],&target,r,none,none);Check("native bombard refresh callback once/no epoch",refreshCalls==refresh+1&&aa.made==1&&CvStackingStrengthCache::SceneEpoch()==epoch);Check("native no expanded new-member reuse after callback",Trial::gStackPacketHits==hits&&got==c.GetStackDanger(&units[1],r,none,none));MOD_EVENTS_CITY_BOMBARD=false;refreshAA=NULL;actors[0].domain=DOMAIN_LAND;}
 {Trial::StackForecastScope trial;target.city=&city;city.garrison=&units[0];city.hp=city.maxHP;Trial::GetCachedStackDanger(&units[0],&target,r,none,none);unsigned builds=Trial::gStackPacketBuilds;city.hp=1;Trial::GetCachedStackDanger(&units[1],&target,r,none,none);Check("native raw city health/protection keys no-epoch change",Trial::gStackPacketBuilds==builds+1);target.city=NULL;}
 {Trial::StackForecastScope trial;actors[0].domain=DOMAIN_AIR;actors[0].ranged=false;unsigned callbacks=airLoadingCallbacks,before=rawSequences;Trial::GetCachedStackDanger(&units[0],&target,r,none,none);Trial::GetCachedStackDanger(&units[1],&target,r,none,none);Check("custom air-melee callback route remains original once per member",airLoadingCallbacks==callbacks+2&&rawSequences==before+2&&Trial::gStackPacketHits==0&&Trial::gStackPacketBuilds==0);actors[0].domain=DOMAIN_LAND;actors[0].ranged=true;}
 {int words[512];unsigned used=0;Check("actual descriptor format/hazards/order",maps[0].NativeCacheDescriptor(target,words,512,used)&&used==8&&words[0]==1&&words[1]==c.m_iImprovementDamage&&words[2]==c.m_iFogCount&&words[4]==1&&words[5]==1&&words[6]==44&&words[7]==0);used=0;Check("descriptor too small no partial writes",!maps[0].NativeCacheDescriptor(target,words,7,used)&&used==0);used=UINT_MAX-1;Check("descriptor unsigned bound cannot overflow",!maps[0].NativeCacheDescriptor(target,words,UINT_MAX,used)&&used==UINT_MAX-1);maps[0].m_bDirty=true;used=0;unsigned refresh=refreshCalls;Check("descriptor dirty is const/no refresh",!maps[0].NativeCacheDescriptor(target,words,512,used)&&used==0&&refreshCalls==refresh);maps[0].m_bDirty=false;}
 for(int mode=0;mode<7;++mode){Trial::StackForecastScope trial;vector<const CvUnit*>roster=r;CvUnit other(91,0,&target);SUnitIDValueContainer f,e;if(mode==0)roster.resize(1);if(mode==1){other.owner=2;roster[4]=&other;}if(mode==2){other=units[4];roster[4]=&other;}if(mode==3)units[0].cargo=true;if(mode==4){f.SetValue(10,1);f.SetValue(11,2);f.m_aExtraStorage.push_back(make_pair(10,3));}if(mode==5){e.SetValue(44,1);e.SetValue(45,2);e.m_aExtraStorage.push_back(make_pair(44,3));}if(mode==6)units[4].domain=DOMAIN_SEA;unsigned raw=rawSequences;Check("native unsupported shape preserves raw numerical path",Trial::GetCachedStackDanger(&units[0],&target,roster,f,e)==c.GetStackDanger(&units[0],roster,f,e)&&Trial::gStackPacketBuilds==0&&rawSequences==raw+1);units[0].cargo=false;units[4].domain=DOMAIN_LAND;Invariant();}
 {Trial::StackForecastScope trial;Trial::GetCachedStackDanger(&units[0],&target,r,none,none);ForeignArgs a={&units[1],&target,&r,&none};HANDLE thread=CreateThread(NULL,0,ForeignNative,&a,0,NULL);Check("native foreign fixture created",thread!=NULL);WaitForSingleObject(thread,INFINITE);CloseHandle(thread);{Trial::StackForecastScope nested;unsigned hits=Trial::gStackPacketHits,builds=Trial::gStackPacketBuilds;Trial::GetCachedStackDanger(&units[1],&target,r,none,none);Check("native nested original fallback no packet side effect",Trial::gStackPacketHits==hits&&Trial::gStackPacketBuilds==builds);}Trial::GetCachedStackDanger(&units[2],&target,r,none,none);Invariant();}
 // Force every allocation in the new packet Store, including VC9 deque's
 // next block after four scalar pointers. Legacy scalar exception policy is
 // deliberately not claimed improved; only the new packet path is tested.
 size_t extra=0;
 for(size_t failure=0;failure<=extra||failure==0;++failure){Trial::StackForecastScope trial;Trial::gStackEntryLimit=20;Trial::gStackKeyPayloadLimit=4000;for(int i=0;i<4;++i){Trial::StackForecastKey k;k.state.push_back(i);k.state.push_back(88);Trial::StoreStackDangerForecast(k,i);}Trial::StackForecastKey key;key.state.assign(15,37);Trial::StackDangerForecastValue value(7);value.memberScores.push_back(make_pair(10,7));value.memberScores.push_back(make_pair(11,9));size_t before=allocationCalls;failAtAllocation=failure?before+failure:0;bool caught=false;try{Trial::StoreStackDangerPacketForecast(key,value);}catch(std::bad_alloc){caught=true;}failAtAllocation=0;if(!failure)extra=allocationCalls-before;else Check("new packet allocation failure observed",caught);Invariant();}
 {Trial::StackForecastScope trial;using namespace CvStackingDiagnostics;planSamples.enabled=true;planSamples.depth=1;planSamples.serial=781;planSamples.epoch=ReadPlanSampleEpoch();Trial::PacketProbeScope probe(0,0);for(int i=0;i<300&&!probe.state->packetResultReuseQueries;++i){SUnitIDValueContainer f;f.SetValue(10,i);Trial::GetCachedStackDanger(&units[0],&target,r,f,none);Trial::GetCachedStackDanger(&units[1],&target,r,f,none);}Check("probe v2 records shared hits separately from local batch",probe.state->packetResultReuseQueries>0);probe.Finish();Check("probe v2 summary schema names shared result",strstr(lastRow,"version=2")&&strstr(lastRow,"packetResultReuseQueries="));planSamples.enabled=false;planSamples.depth=0;}
 Check("outer scope releases native packet scratch",Trial::gStackPacketScratch.key.state.empty()&&Trial::gStackPacketScratch.source.empty()&&Trial::gStackPacketScratch.value.memberScores.capacity()==0&&Trial::gStackKeyPayloadBytes==0);
 printf("shared packet ACTUAL NATIVE STAGE:%u checks,%u failures; full old/new wrappers, same budgets, queried int fast hits; no native ROI\n",checks,failures);return failures?1:0;
}
'''
code=headers+base+services+implementation+tests;(out/'test.cpp').write_text(code,encoding='utf-8')
if '--emit-only' in sys.argv:print('Actual native shared-packet fixture emitted; no compilation');sys.exit(0)
vc=root/'work/toolchain/sdk/admin/vc9/Program Files/Microsoft Visual Studio 9.0';sdk=root/'work/toolchain/sdk/windows';env=os.environ.copy();env['PATH']=str(vc/'Vc7/bin')+';'+str(vc/'Common7/IDE')+';'+env.get('PATH','');env['INCLUDE']=str(root/'work/toolchain/sdk/vc9/include')+';'+str(sdk/'Include');env['LIB']=str(root/'work/toolchain/sdk/vc9/lib')+';'+str(sdk/'Lib')
for k in ('CL','_CL_','LINK'):env.pop(k,None)
exe=out/'test.exe';built=subprocess.run([str(vc/'Vc7/bin/cl.exe'),'/nologo','/EHsc','/MT','/O2','/Z7','/D_SECURE_SCL=0','/D_HAS_ITERATOR_DEBUGGING=0',str(out/'test.cpp'),'/Fe'+str(exe)],cwd=out,env=env,capture_output=True,text=True,timeout=60);(out/'compile.log').write_text(built.stdout+built.stderr)
if built.returncode:print(built.stdout+built.stderr);sys.exit(built.returncode)
run=subprocess.run([str(exe)],cwd=out,capture_output=True,text=True,timeout=40);print(run.stdout+run.stderr,end='');(out/'result.json').write_text(json.dumps(dict(returncode=run.returncode,output=run.stdout+run.stderr,control=manifest['control'],production_untouched=True,bound_current_production=production,actual_current_source_sha256={n:hashlib.sha256(s.encode()).hexdigest() for n,s in live.items()} if production else {},actual_native_wrapper_and_storage=True,scalar_prefix_math_key_byte_proofs=True,stage_hashes=manifest['candidate_sha256'],fixture_sha256=hashlib.sha256(code.encode()).hexdigest(),scope='Complete actual frozen77 original and integrated current/staged native wrappers/key/scratch/FIFO/accounting plus exact complete math under deterministic engine services. Strict3file current binding when --production. No DLL/native ROI claim.'),indent=2));sys.exit(run.returncode)
