"""Actual staged first-wave/offensive module and army-core regression; no game."""
from pathlib import Path
import ast,hashlib,json,os,re,subprocess,sys
ROOT=Path(__file__).resolve().parents[1];BASE='d792b4bcb';OUT=ROOT/'work/first-wave-regression';OUT.mkdir(exist_ok=True)
subprocess.run([sys.executable,str(ROOT/'work/prepare-first-wave.py')],check=True,capture_output=True)
stage=ROOT/'work/first-wave-staged';proof=json.loads((stage/'proof.json').read_text())
original={n:(stage/('control-'+n)).read_text(encoding='utf-8-sig') for n in proof['original_hashes']};trial={n:(stage/n).read_text(encoding='utf-8-sig') for n in original}
for n in original:assert hashlib.sha256(original[n].encode()).hexdigest()==proof['original_hashes'][n] and hashlib.sha256(trial[n].encode()).hexdigest()==proof['candidate_hashes'][n]
template=(ROOT/'work/test-offensive-support.py').read_text(encoding='utf-8-sig');prefix=template[:template.index("tests=r'''")]
ns={'__file__':str(ROOT/'work/test-offensive-support.py')};exec(compile(prefix,'tracked deterministic military/offensive services','exec'),ns)
stubs=ns['stubs'];clean=ns['clean'];policy=ns['policy']
stubs=stubs.replace('int id,owner,m_eOwner,strength,damage,maxhp,productionType,productionTurns,productionOperation;', 'mutable int forecastReads,strengthReads;int forecastRate;bool forecastComplete;int id,owner,m_eOwner,strength,damage,maxhp,productionType,productionTurns,productionOperation;')
stubs=stubs.replace('CvCity(int n,CvPlot*pp):id(n)', 'CvCity(int n,CvPlot*pp):forecastReads(0),strengthReads(0),forecastRate(16),forecastComplete(false),id(n)')
stubs=stubs.replace('int getStrengthValue()const{return strength;}', 'int getStrengthValue()const{++strengthReads;return strength;}int GetAssaultHealingForecast(int,int,bool*complete=NULL)const{++forecastReads;if(complete)*complete=forecastComplete;return blocked?0:forecastRate;}')
stubs+='\n#include <new>\nstatic bool failWaveRecord=false,failCoreRows=false;'
stubs=stubs.replace('int getUnitType()const{return type;}', 'int getUnitType()const{return type;}int getMoves()const{return moves?120:0;}bool isSetUpForRangedAttack()const{return false;}')

def fun(s,sig):
 a=s.index(sig);b=s.index('{',a)+1;d=1
 while d:d+=(s[b]=='{')-(s[b]=='}');b+=1
 return s[a:b]
previous=dict(trial);previousCore=(ROOT/'work/first-wave-core-before-filter.cpp').read_text(encoding='utf-8-sig').rstrip()
currentCore=fun(trial['CvStackingOffensiveAI.cpp'],'    bool TryReadyCoreForArmy(')
previous['CvStackingOffensiveAI.cpp']=previous['CvStackingOffensiveAI.cpp'].replace(currentCore,previousCore,1)
assert hashlib.sha256(previous['CvStackingOffensiveAI.cpp'].encode()).hexdigest()=='fa0d9650738194fc8763b88de2447812507df125fb01e90c9825ca8a7e2799f4', 'Only frozen core-readiness body may change'
module=''
for name,text in [('Baseline',original),('PreviousWave',previous),('Trial',trial)]:
 alias='namespace CvStackingAI{using ::CvStackingAI::Enabled;using ::CvStackingAI::UnitStrength;using ::CvStackingAI::RetainCityUnit;static int Setting(const char*n,int f){return CvStacking::GetInt(n,f);}}\n'
 body=clean(text['CvStackingOffensiveAI.cpp']).replace('try{o.waveRows.push_back(', 'try{if(failWaveRecord){failWaveRecord=false;throw std::bad_alloc();}o.waveRows.push_back(').replace('eligibleRows.reserve(o.waveRows.size());','if(failCoreRows){failCoreRows=false;throw std::bad_alloc();}eligibleRows.reserve(o.waveRows.size());')
 module+='namespace '+name+'{\n'+alias+re.sub(r'^class Cv\w+;\n','',clean(text['CvStackingOffensiveAI.h']),flags=re.M)+body+'\nnamespace CvStackingAI{'+fun(text['CvStackingAI.cpp'],'    bool ReadyWithAvailableUnits(')+'\n}\n}\n'
tests=r'''
static int checks=0,failed=0;static void Check(const char*name,bool ok){++checks;if(!ok){++failed;printf("FAIL %s\n",name);}}
static void Reset(){Baseline::CvStackingOffensiveAI::Reset();PreviousWave::CvStackingOffensiveAI::Reset();Trial::CvStackingOffensiveAI::Reset();for(int i=0;i<MAX_PLAYERS;++i){players[i]=CvPlayer();players[i].id=i;}GC.game.turn=100;GC.map.plots.clear();options.clear();capacity=2;stackEnabled=true;retaliation=20;captureDamage=1;failCoreRows=false;}
struct Scenario{
 CvPlot target,front,rear;CvCity city;CvArmyAI army;CvAIOperation op;CvUnit units[32];
 Scenario(int count=8,int domain=DOMAIN_LAND):target(10,0,0),front(11,1,0),rear(12,5,0),city(7,&target){
  Reset();target.owner=city.owner=city.m_eOwner=1;target.coastal=true;front.water=rear.water=domain==DOMAIN_SEA;city.strength=1100;city.maxhp=364;army.domain=domain;army.id=1;army.op=1;army.owner=0;op.id=1;op.owner=0;op.enemy=1;op.target=&target;op.army=&army;op.started=80;op.type=domain==DOMAIN_SEA?AI_OPERATION_CITY_ATTACK_NAVAL:AI_OPERATION_CITY_ATTACK_LAND;players[0].op=&op;players[0].armies.push_back(&army);players[0].war=true;GC.map.plots[10]=&target;GC.map.plots[11]=&front;GC.map.plots[12]=&rear;
  for(int i=0;i<count;++i){units[i]=CvUnit(100+i);CvUnit&u=units[i];u.owner=0;u.army=1;u.domain=domain;u.eta=0;u.end=&front;u.position=&front;u.cityShot=32;players[0].units.push_back(&u);front.units.push_back(&u);army.slots.push_back(CvArmyFormationSlot(u.id,true));}
 }
 void Ranged(int i,bool siege=false){units[i].ranged=true;units[i].capture=false;units[i].rs=40;units[i].role=siege?UNITAI_CITY_BOMBARD:UNITAI_DEFENSE;units[i].info.role=units[i].role;}
 void Late(int i,int eta){units[i].position=&rear;units[i].eta=eta;}
 int Paths()const{int result=0;for(int i=0;i<32;++i)result+=units[i].pathCalls;return result;}
};
int main(){
 {Scenario s;for(int i=5;i<8;++i)s.Ranged(i);s.units[7].cityShot=29;s.Late(7,2);Baseline::CvStackingOffensiveAI::ObserveOperation(&s.op);Trial::CvStackingOffensiveAI::ObserveOperation(&s.op);int paths=s.Paths();Baseline::CvStackingOffensiveAI::AssaultPlan old=Baseline::CvStackingOffensiveAI::AssessAssault(0,&s.city,DOMAIN_LAND);int oldPaths=s.Paths()-paths;paths=s.Paths();Trial::CvStackingOffensiveAI::AssaultPlan now=Trial::CvStackingOffensiveAI::AssessAssault(0,&s.city,DOMAIN_LAND);Check("Rome55 late optional member no longer blocks sufficient first wave",!old.ready&&now.ready&&now.waveUnits==7&&now.failedMask==0);Check("first wave uses no additional assault paths",s.Paths()-paths<=oldPaths);paths=s.Paths();Trial::CvStackingOffensiveAI::AssessAssault(0,&s.city,DOMAIN_LAND);Check("objective assessment once per turn",s.Paths()==paths);for(int missing=0;missing<8;++missing)s.army.slots.push_back(CvArmyFormationSlot(-1,true));Check("original formation count holds missing reserves",!Baseline::CvStackingAI::ReadyWithAvailableUnits(&s.op,&s.army));Check("own army core can leave optional required formation slots behind",Trial::CvStackingAI::ReadyWithAvailableUnits(&s.op,&s.army));capacity=9;Check("tech capacity does not raise hard first-wave minimum",Trial::CvStackingOffensiveAI::AssessAssault(0,&s.city,DOMAIN_LAND).ready);s.units[0].hp=20;bool core=true;Check("one wounded optional member does not veto sufficient unchanged core",Trial::CvStackingOffensiveAI::TryReadyCoreForArmy(&s.op,&s.army,core)&&core);}
 {Scenario s;for(int i=1;i<8;++i)s.Ranged(i);s.Late(0,2);Trial::CvStackingOffensiveAI::ObserveOperation(&s.op);Trial::CvStackingOffensiveAI::AssaultPlan p=Trial::CvStackingOffensiveAI::AssessAssault(0,&s.city,DOMAIN_LAND);Check("slow essential capturer still holds wave",!p.ready&&(p.failedMask&Trial::ASSAULT_CAPTURE));}
 {Scenario s;s.city.strength=2500;for(int i=5;i<8;++i)s.Ranged(i,true);s.Late(5,2);s.Late(6,2);s.Late(7,2);Trial::CvStackingOffensiveAI::ObserveOperation(&s.op);Trial::CvStackingOffensiveAI::AssaultPlan p=Trial::CvStackingOffensiveAI::AssessAssault(0,&s.city,DOMAIN_LAND);Check("late essential siege is not optional",!p.ready&&(p.failedMask&Trial::ASSAULT_SIEGE));}
 {Scenario s(21);s.city.strength=4000;s.city.maxhp=446;s.city.forecastRate=23;capacity=7;for(int i=8;i<16;++i)s.Ranged(i,true);for(int i=16;i<21;++i)s.Ranged(i);for(int i=18;i<21;++i)s.Late(i,3);Trial::CvStackingOffensiveAI::ObserveOperation(&s.op);Trial::CvStackingOffensiveAI::AssaultPlan p=Trial::CvStackingOffensiveAI::AssessAssault(0,&s.city,DOMAIN_LAND);Check("Dublin21 and8 siege yields sufficient early core",p.ready&&p.waveUnits==18&&p.waveSiege==8);}
 {Scenario s(14,DOMAIN_SEA);s.city.strength=3900;s.city.maxhp=470;s.city.forecastRate=23;capacity=7;for(int i=7;i<14;++i)s.Ranged(i);for(int i=0;i<14;++i)s.units[i].cityShot=19;Trial::CvStackingOffensiveAI::ObserveOperation(&s.op);Trial::CvStackingOffensiveAI::AssaultPlan p=Trial::CvStackingOffensiveAI::AssessAssault(0,&s.city,DOMAIN_SEA);Check("14 ship fleet is not forced to wait for desired22",p.ready&&p.readyUnits==14&&p.desiredUnits>14&&p.waveDamage==266);}
 {Scenario s;s.city.strength=30000;for(int i=5;i<8;++i)s.Ranged(i,true);Trial::CvStackingOffensiveAI::ObserveOperation(&s.op);Trial::CvStackingOffensiveAI::AssaultPlan p=Trial::CvStackingOffensiveAI::AssessAssault(0,&s.city,DOMAIN_LAND);Check("high threat blocks weak core",!p.ready&&(p.failedMask&Trial::ASSAULT_STRENGTH));}
 {Scenario s;s.city.strength=0;for(int i=5;i<8;++i)s.Ranged(i);Trial::CvStackingOffensiveAI::ObserveOperation(&s.op);Trial::CvStackingOffensiveAI::AssaultPlan p=Trial::CvStackingOffensiveAI::AssessAssault(0,&s.city,DOMAIN_LAND);Check("unknown strength is not automatic superiority",!p.ready&&(p.failedMask&Trial::ASSAULT_UNKNOWN));}
 {Scenario s;for(int i=5;i<8;++i)s.Ranged(i);for(int i=0;i<8;++i)s.units[i].cityShot=3;Trial::CvStackingOffensiveAI::ObserveOperation(&s.op);Trial::CvStackingOffensiveAI::AssaultPlan p=Trial::CvStackingOffensiveAI::AssessAssault(0,&s.city,DOMAIN_LAND);Check("healthy count cannot compensate for inadequate sustained damage",!p.ready&&(p.failedMask&Trial::ASSAULT_DAMAGE));}
 {Scenario s;players[0].war=false;for(int i=5;i<8;++i)s.Ranged(i);s.Late(7,2);Check("voluntary opening uses sufficient coherent staged force",Trial::CvStackingOffensiveAI::OpeningReady(&s.op,&s.army));int paths=s.Paths();Check("same-turn opening cache prevents repeated routes",Trial::CvStackingOffensiveAI::OpeningReady(&s.op,&s.army)&&s.Paths()==paths);s.units[0].capture=false;Check("same-turn changed capture role invalidates declaration readiness",!Trial::CvStackingOffensiveAI::OpeningReady(&s.op,&s.army)&&s.Paths()==paths);players[0].war=true;Check("forced or existing war bypasses voluntary declaration gate",Trial::CvStackingOffensiveAI::ReadyToDeclare(0,1));}
 {Scenario s;players[0].war=false;s.target.visible=false;for(int i=5;i<8;++i)s.Ranged(i);Check("hidden city keeps legacy scouting policy",Trial::CvStackingOffensiveAI::OpeningReady(&s.op,&s.army));Check("hidden city no healing or strength peek",s.city.forecastReads==0&&s.city.strengthReads==0);}
 {Scenario s;players[0].war=false;for(int i=5;i<8;++i)s.Ranged(i);s.front.route=false;Check("closed-border operation route cannot fake opening",!Trial::CvStackingOffensiveAI::OpeningReady(&s.op,&s.army));}
 {Scenario s;for(int i=5;i<8;++i)s.Ranged(i);options["AIAssaultWaveMaximumRecords"]=4;Trial::CvStackingOffensiveAI::ObserveOperation(&s.op);Trial::CvStackingOffensiveAI::AssaultPlan p=Trial::CvStackingOffensiveAI::AssessAssault(0,&s.city,DOMAIN_LAND);Check("bounded record overflow preserves original policy and marks unknown",p.ready&&(p.failedMask&Trial::ASSAULT_UNKNOWN));}
 {Scenario s(7);std::vector<Trial::AssaultWaveUnit> rows;for(int i=0;i<7;++i){if(i<2)s.Ranged(i,true);s.units[i].cityShot=i<4?50:300;rows.push_back(Trial::AssaultWaveUnit(&s.units[i],i<4?0:1,s.units[i].cityShot,20,&s.target));}Trial::AssaultWave w=Trial::SelectFirstWave(rows,4,2,0,10,125,100,0,1,0);Check("invalid higher-damage later cohort cannot replace valid first wave",w.failed==0&&w.units==4&&w.first==0);}
 {Scenario s;for(int i=3;i<8;++i)s.Ranged(i,true);CvArmyAI unrelated;unrelated.id=2;unrelated.op=2;players[0].armies.push_back(&unrelated);for(int i=3;i<8;++i){s.units[i].army=2;s.army.slots[i].id=-1;unrelated.slots.push_back(CvArmyFormationSlot(s.units[i].id,true));}Trial::CvStackingOffensiveAI::ObserveOperation(&s.op);bool ready=true;Check("unrelated army power cannot release own undersized core",Trial::CvStackingOffensiveAI::TryReadyCoreForArmy(&s.op,&s.army,ready)&&!ready);}
 {Scenario s;for(int i=1;i<8;++i)s.Ranged(i);Trial::CvStackingOffensiveAI::ObserveOperation(&s.op);Trial::CvStackingOffensiveAI::AssessAssault(0,&s.city,DOMAIN_LAND);s.units[0].dead=true;bool ready=true;Check("deleted cached core cannot leak through count fallback",Trial::CvStackingOffensiveAI::TryReadyCoreForArmy(&s.op,&s.army,ready)&&!ready);}
 {Scenario s;players[0].war=false;for(int i=5;i<8;++i)s.Ranged(i);Check("target cache initially ready",Trial::CvStackingOffensiveAI::OpeningReady(&s.op,&s.army));int paths=s.Paths();s.target.owner=s.city.owner=2;Check("same-turn target ownership change rejects without route retry",!Trial::CvStackingOffensiveAI::OpeningReady(&s.op,&s.army)&&s.Paths()==paths);Trial::CvStackingOffensiveAI::Reset();Check("opening cache cleared on load/reset",Trial::openingForecasts.empty());}
 {Scenario s;for(int i=5;i<8;++i)s.Ranged(i);s.Late(6,2);s.Late(7,2);Trial::CvStackingOffensiveAI::ObserveOperation(&s.op);Trial::assaultQueries[0]=options["AIAssaultPathQueriesPerTurn"]=64;Trial::CvStackingOffensiveAI::AssaultPlan p=Trial::CvStackingOffensiveAI::AssessAssault(0,&s.city,DOMAIN_LAND);Check("sufficient known core is not blocked by optional budget-exhausted arrivals",p.ready);}
 {Scenario s;for(int i=5;i<8;++i)s.Ranged(i);Trial::CvStackingOffensiveAI::ObserveOperation(&s.op);failWaveRecord=true;Trial::CvStackingOffensiveAI::AssaultPlan p=Trial::CvStackingOffensiveAI::AssessAssault(0,&s.city,DOMAIN_LAND);failWaveRecord=false;Check("optional wave-record bad_alloc falls back to original readiness",p.ready&&!Trial::objectives.begin()->second.waveComplete&&(p.failedMask&Trial::ASSAULT_UNKNOWN));}
 {Scenario s;players[0].war=false;for(int i=5;i<8;++i)s.Ranged(i);options["AIAssaultWaveMaximumRecords"]=4;Check("prewar record overflow preserves original readiness",Trial::CvStackingOffensiveAI::OpeningReady(&s.op,&s.army));int paths=s.Paths();Check("fallback uses original live policy on next call",Trial::CvStackingOffensiveAI::OpeningReady(&s.op,&s.army));Check("fallback original route scan remains bounded",s.Paths()-paths==0);}
 {Scenario s;for(int i=5;i<8;++i)s.Ranged(i);Trial::CvStackingOffensiveAI::ObserveOperation(&s.op);Trial::CvStackingOffensiveAI::AssessAssault(0,&s.city,DOMAIN_LAND);Trial::Objective& o=Trial::objectives.begin()->second;o.captureID=105;o.captureOwner=0;o.captureEta=0;for(size_t i=0;i<o.waveRows.size();++i){o.waveRows[i].army=1;o.waveRows[i].roles&=~1;}bool ready=true;Check("globally reserved capturer cannot invent own cohort capture role",Trial::CvStackingOffensiveAI::TryReadyCoreForArmy(&s.op,&s.army,ready)&&!ready);}
 {Scenario s;for(int i=5;i<8;++i)s.Ranged(i);Trial::CvStackingOffensiveAI::ObserveOperation(&s.op);Trial::CvStackingOffensiveAI::AssessAssault(0,&s.city,DOMAIN_LAND);s.target.owner=s.city.owner=2;bool ready=true;Check("known changed target owner never releases old-enemy core",Trial::CvStackingOffensiveAI::TryReadyCoreForArmy(&s.op,&s.army,ready)&&!ready);}
 {Scenario s;for(int i=1;i<8;++i)s.Ranged(i);Trial::CvStackingOffensiveAI::ObserveOperation(&s.op);Trial::CvStackingOffensiveAI::AssessAssault(0,&s.city,DOMAIN_LAND);s.units[0].processed=true;bool ready=true;Check("processed core invalidates admission without new paths",Trial::CvStackingOffensiveAI::TryReadyCoreForArmy(&s.op,&s.army,ready)&&!ready);}
 {Scenario s(5);s.city.strength=2500;for(int i=1;i<5;++i)s.Ranged(i,i<=2);for(int i=0;i<5;++i)s.units[i].cityShot=50;s.units[4].army=-1;PreviousWave::CvStackingOffensiveAI::ObserveOperation(&s.op);Trial::CvStackingOffensiveAI::ObserveOperation(&s.op);PreviousWave::CvStackingOffensiveAI::AssessAssault(0,&s.city,DOMAIN_LAND);Trial::CvStackingOffensiveAI::AssessAssault(0,&s.city,DOMAIN_LAND);s.units[4].processed=true;int paths=s.Paths(),heals=s.city.forecastReads;bool old=true,ready=false;Check("prior all-row veto reproduces optional consumed-support delay",PreviousWave::CvStackingOffensiveAI::TryReadyCoreForArmy(&s.op,&s.army,old)&&!old);Check("four unchanged own units launch despite processed loose optional row",Trial::CvStackingOffensiveAI::TryReadyCoreForArmy(&s.op,&s.army,ready)&&ready);Check("filtered core uses no new paths and retains one healing call",s.Paths()==paths&&s.city.forecastReads-heals==1);}
 {Scenario s(6);s.city.strength=2500;for(int i=1;i<6;++i)s.Ranged(i,i<=2);for(int i=0;i<6;++i)s.units[i].cityShot=50;s.Late(5,2);s.units[5].hp=80;Trial::CvStackingOffensiveAI::ObserveOperation(&s.op);Trial::CvStackingOffensiveAI::AssessAssault(0,&s.city,DOMAIN_LAND);s.units[5].hp=100;int paths=s.Paths();bool ready=false;Check("five unchanged own units launch despite healed optional row",Trial::CvStackingOffensiveAI::TryReadyCoreForArmy(&s.op,&s.army,ready)&&ready);Check("optional healing does not reopen assessment paths",s.Paths()==paths);}
 {Scenario s(5);s.city.strength=2500;for(int i=1;i<5;++i)s.Ranged(i,i<=2);for(int i=0;i<5;++i)s.units[i].cityShot=50;Trial::CvStackingOffensiveAI::ObserveOperation(&s.op);Trial::CvStackingOffensiveAI::AssessAssault(0,&s.city,DOMAIN_LAND);s.units[4].position=&s.rear;bool ready=false;Check("moved optional row is omitted rather than vetoing ready own four",Trial::CvStackingOffensiveAI::TryReadyCoreForArmy(&s.op,&s.army,ready)&&ready);}
 {Scenario s(5);s.city.strength=2500;for(int i=1;i<5;++i)s.Ranged(i,i<=2);for(int i=0;i<5;++i)s.units[i].cityShot=50;Trial::CvStackingOffensiveAI::ObserveOperation(&s.op);Trial::CvStackingOffensiveAI::AssessAssault(0,&s.city,DOMAIN_LAND);s.units[0].dead=true;Trial::Objective&o=Trial::objectives.begin()->second;o.wavePathUnknown=true;bool ready=true;Check("dead essential capturer stays a known rejection despite unrelated path uncertainty",Trial::CvStackingOffensiveAI::TryReadyCoreForArmy(&s.op,&s.army,ready)&&!ready);Check("filter leaves original strategic rows intact",o.waveRows.size()==5&&o.assaultTurn==GC.game.turn);}
 {Scenario s(5);s.city.strength=2500;for(int i=1;i<5;++i)s.Ranged(i,i<=2);for(int i=0;i<5;++i)s.units[i].cityShot=50;Trial::CvStackingOffensiveAI::ObserveOperation(&s.op);Trial::CvStackingOffensiveAI::AssessAssault(0,&s.city,DOMAIN_LAND);s.units[1].hp=20;bool ready=true;Check("essential siege wound removes its role even with four healthy own units remaining",Trial::CvStackingOffensiveAI::TryReadyCoreForArmy(&s.op,&s.army,ready)&&!ready);}
 {Scenario s(4);s.city.strength=2500;for(int i=1;i<4;++i)s.Ranged(i,i<=2);for(int i=0;i<4;++i)s.units[i].cityShot=50;Trial::CvStackingOffensiveAI::ObserveOperation(&s.op);Trial::CvStackingOffensiveAI::AssessAssault(0,&s.city,DOMAIN_LAND);s.units[3].dead=true;bool ready=true;Check("dead own member cannot satisfy mandatory four-own core count",Trial::CvStackingOffensiveAI::TryReadyCoreForArmy(&s.op,&s.army,ready)&&!ready);}
 {Scenario s(5);s.city.strength=2500;for(int i=0;i<4;++i)s.Ranged(i,i<2);for(int i=0;i<5;++i)s.units[i].cityShot=50;s.units[4].army=-1;Trial::CvStackingOffensiveAI::ObserveOperation(&s.op);Trial::CvStackingOffensiveAI::AssessAssault(0,&s.city,DOMAIN_LAND);Trial::commitments[Trial::Key(0,s.units[4].id)].goal=Trial::ObjectiveKey(0,99,DOMAIN_LAND);bool ready=true;Check("same-plot loose capturer reassigned to another goal is not credited",Trial::CvStackingOffensiveAI::TryReadyCoreForArmy(&s.op,&s.army,ready)&&!ready);}
 {Scenario s(5);s.city.strength=2500;for(int i=1;i<5;++i)s.Ranged(i,i<=2);for(int i=0;i<5;++i)s.units[i].cityShot=50;Trial::CvStackingOffensiveAI::ObserveOperation(&s.op);Trial::CvStackingOffensiveAI::AssessAssault(0,&s.city,DOMAIN_LAND);int paths=s.Paths();bool ready=true;failCoreRows=true;Check("optional filtering metadata bad_alloc returns unknown policy fallback",!Trial::CvStackingOffensiveAI::TryReadyCoreForArmy(&s.op,&s.army,ready)&&!ready);Check("metadata failure keeps original rows and cached assessment intact",Trial::objectives.begin()->second.waveComplete&&Trial::objectives.begin()->second.waveRows.size()==5&&s.Paths()==paths);}
 printf("FIRST WAVE: %d checks, %d failures\n",checks,failed);return failed?1:0;
}
'''
code=stubs+policy+module+tests;(OUT/'test.cpp').write_text(code,encoding='utf-8');binding=dict(proof,fixture_sha256=hashlib.sha256(code.encode()).hexdigest(),previous_component_sha256='fa0d9650738194fc8763b88de2447812507df125fb01e90c9825ca8a7e2799f4',only_core_readiness_changed_from_previous=True,scope='Actual complete DLL96 baseline, frozen previous-wave and candidate offensive modules plus ReadyWithAvailableUnits bodies; strict previous whole-source hash restoration proves core-only follow-up; deterministic native services/path outcomes/healing boundary, shared native healing separately tested; fixture-only faults at optional wave-record push/catch and filtered-vector reserve seams; not campaign efficacy or timing evidence.')
(OUT/'proof.json').write_text(json.dumps(binding,indent=2)+'\n')
if '--emit-only' in sys.argv:print(OUT/'test.cpp');sys.exit(0)
vc=ROOT/'work/toolchain/sdk/admin/vc9/Program Files/Microsoft Visual Studio 9.0';sdk=ROOT/'work/toolchain/sdk/windows';env=os.environ.copy();env['PATH']=str(vc/'Vc7/bin')+';'+str(vc/'Common7/IDE')+';'+env.get('PATH','');env['INCLUDE']=str(ROOT/'work/toolchain/sdk/vc9/include')+';'+str(sdk/'Include');env['LIB']=str(ROOT/'work/toolchain/sdk/vc9/lib')+';'+str(sdk/'Lib')
for n in ('CL','_CL_','LINK'):env.pop(n,None)
build=subprocess.run([str(vc/'Vc7/bin/cl.exe'),'/nologo','/EHsc','/MT','/O2',str(OUT/'test.cpp'),'/Fo'+str(OUT/'test.obj'),'/Fe'+str(OUT/'test.exe')],cwd=OUT,env=env,capture_output=True,text=True,timeout=60);(OUT/'compile.log').write_text(build.stdout+build.stderr)
if build.returncode:print(build.stdout+build.stderr);sys.exit(build.returncode)
run=subprocess.run([str(OUT/'test.exe')],cwd=OUT,capture_output=True,text=True,timeout=45);print(run.stdout+run.stderr);binding.update(compile_returncode=build.returncode,test_returncode=run.returncode,output=run.stdout+run.stderr);(OUT/'result.json').write_text(json.dumps(binding,indent=2)+'\n');sys.exit(run.returncode)
